[phases.setup]
aptPkgs = ["libgomp1"]
nixPkgs = ["python310"]

[phases.install]
cmds = ["python3.10 -m pip install -r requirements.txt"]

[start]
cmd = "python3.10 -m uvicorn api:app --host 0.0.0.0 --port $PORT"